"""Add sr_no to DeviceInventory

Revision ID: 5dfdad611b92
Revises: 
Create Date: 2025-05-16 14:35:56.505583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5dfdad611b92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    with op.batch_alter_table('device_inventory', schema=None) as batch_op:
        batch_op.alter_column('sr_no',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_inventory', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('sr_no',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('serial_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='devices_pkey')
    )
    # ### end Alembic commands ###
